//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FidelidadeCPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{F9};{DIVIDE};{DOWN};{DOWN};{DOWN};{ENTER};{ADD}")]
        public string DESCONTO_FIDELIDADE {
            get {
                return ((string)(this["DESCONTO_FIDELIDADE"]));
            }
            set {
                this["DESCONTO_FIDELIDADE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MQM-HOME\\SQLEXPRESS;Initial Catalog=Avenca;Persist Security Info=Fals" +
            "e;User ID=miguelqm;Password=migSql@#;Connection Timeout=5")]
        public string AvencaConnectionString {
            get {
                return ((string)(this["AvencaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MQM-HOME\\SQLEXPRESS;Initial Catalog=Avenca;Persist Security Info=Fals" +
            "e;User ID=miguelqm;Password=***;Connection Timeout=5")]
        public string AvencaLibConnectionString {
            get {
                return ((string)(this["AvencaLibConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\Temp")]
        public string PRTSCRPATH {
            get {
                return ((string)(this["PRTSCRPATH"]));
            }
            set {
                this["PRTSCRPATH"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MQM-HOME\\SQLEXPRESS;Initial Catalog=Avenca;Integrated Security=True")]
        public string AvencaConnectionString1 {
            get {
                return ((string)(this["AvencaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000;{F9};{DIVIDE};{DOWN};{DOWN};{ENTER};{ADD}")]
        public string f {
            get {
                return ((string)(this["f"]));
            }
            set {
                this["f"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000;{F9};{DIVIDE};{DOWN};{ENTER};{ADD}")]
        public string g {
            get {
                return ((string)(this["g"]));
            }
            set {
                this["g"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100;{F9};{DIVIDE};{ENTER};{ADD}")]
        public string SPACE {
            get {
                return ((string)(this["SPACE"]));
            }
            set {
                this["SPACE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100{F9};{DIVIDE};{DOWN};{DOWN};{DOWN};{ENTER};{ADD}")]
        public string c {
            get {
                return ((string)(this["c"]));
            }
            set {
                this["c"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800;{F6};T;{ENTER}")]
        public string t {
            get {
                return ((string)(this["t"]));
            }
            set {
                this["t"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800;{F6};H;{ENTER}")]
        public string h {
            get {
                return ((string)(this["h"]));
            }
            set {
                this["h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800;{F6};B;{ENTER}")]
        public string b {
            get {
                return ((string)(this["b"]));
            }
            set {
                this["b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800;{F6};P;{ENTER}")]
        public string p {
            get {
                return ((string)(this["p"]));
            }
            set {
                this["p"] = value;
            }
        }
    }
}
